name: systeminfo
version: '4.2.3'
summary: Simple program showing system information
description: |
  A program that displays basic information about the system and resources
grade: stable
base: core18
license: GPL-2.0

apps:
  systeminfo:
    command: systeminfo
    plugs:
      - home
      - network
      - network-bind
      - removable-media

parts:
  systeminfo:
    plugin: cmake
    source: .
    build-packages:
      - cmake
      - make